### ISSUE TITLE
Format code by default with `dotlin compile`, add `--no-format`

### ISSUE THREAD

**Issue by eggnstone** [dirtlang/dirt#105]
Please format the generated code in some way.
This would help reading the code and debug error messages. I also don't think that it saves time in any way.
I know that I could format it myself but generated should not be manually touched and also gets regenerated from time to time.

**Comment by wilkomanger** [comment]
Yes this will be added back before the v0.1.0 release :+1: Before there was a `--format` options, but most likely I'll make it the default and it can be turned off with `--no-format`
