### ISSUE TITLE
String .contains() /.substring() / .isEmpty() / .isNotEmpty() not supported

### ISSUE THREAD

**Issue by eggnstone** [dirtlang/dirt#65]
It seems that String.contains() is not supported (or mistranslated?)

How can I work-around that?
Also, println() is not supported. Should I create another issue for that, too?

Simple.kt:
```
class Simple
{
    fun x()
    {
        val s: String = "abc"
        if (s.contains("a"))
            println("a")
        else
            println("no a")
    }
}
```
Error:
```
lib\Simple.kt:6:15: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline operator fun IntRange.contains(element: Int?): Boolean defined in kotlin.ranges
        if (s.contains("a"))
              ^
lib\Simple.kt:7:13: error: unresolved reference: println
            println("a")
            ^
lib\Simple.kt:9:13: error: unresolved reference: println
            println("no a")
            ^
```

**Comment by eggnstone** [comment]
Also
- String.substring()
- String.isNotEmpty
- arrayListOf()

**Comment by wilkomanger** [comment]
Thanks for the report! Indeed that's expected behavior for now, currently only a minimal set of the Kotlin stdlib and `dart:core` is available, some will come before 0.1.0 and some after, depending on the method. And some not at all, such as `arrayListOf`, since that's a Kotlin/JVM method we won't need. For that one you can just use `mutableListOf`, that works already now :+1:

**Comment by eggnstone** [comment]
A list of workarounds I had to implement can be found in this source code:

- kotlin minOf

- List<T>.isEmpty

- String.contains
- String.isEmpty
- String.isNotEmpty
- String.repeat
- String.replace
- String.split
- String.startsWith
- String.substring
- String.trim

https://github.com/eggnstone/DartFormatJetbrainsPlugin/blob/master/src/main/kotlin/dev/eggnstone/plugins/jetbrains/dartformat/dotlin/DotlinTools.kt

**Comment by wilkomanger** [comment]
Thanks! Yeah those (and basically all of the Kotlin stdlib + dart:core) will be added in the future :+1:
